function testToolbox(varargin)
    projectRootDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    %matbox.installRequirements(fullfile(projectRootDir, 'tests'))
    matbox.tasks.testToolbox(projectRootDir, ...
        "SourceFolderName", "+ndr", ...
        "ToolsFolderName", "tools", ...
        varargin{:})
end
