name: Test code

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
      
  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow-test-toolbox:
    name: Test
    uses: ehennestad/matbox-actions/.github/workflows/test-code-workflow.yml@v1
    with:
      source_directory: '+ndr'
      tests_directory: 'tools/tests'
      matlab_use_cache: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
